In [1]:
import csv
from geopy.geocoders import Nominatim
import pandas as pd

In [2]:
def geocode_address(address):
    geolocator = Nominatim(user_agent="geocoder_app")
    location = geolocator.geocode(address)

    if location:
        latitude = location.latitude
        longitude = location.longitude 
        return latitude, longitude 
    else:
        return None, None

In [4]:
# import data

df = pd.read_csv("costar-affordable-housing-data.csv", index_col=0)
df.head()

,Address,Building Name,Class,Units,RBA/GLA,Secondary Type,Submarket,City,Land(AC),Built/Renov,Total Buildings,Stories,Vacancy %,Rent Type,Affordable Type,Parking Spaces/Unit,Parking Spaces
0,3501 1st Ave,3501 1st Avenue,C,22,"16,354",Apartments,Hillcrest,San Diego,0.31,1960,1.0,2.0,2.3,Affordable,Rent Restricted,0.73,16.0
1,3534 5th Ave,Strauss on Fifth,B,141,"261,900",Apartments,Hillcrest,San Diego,0.98,2019,1.0,6.0,0.8,Market/Affordable,Affordable Units,NaN,NaN
2,3754 5th Ave,Hillcrest Inn,C,46,"47,000",Apartments,Hillcrest,San Diego,0.16,1988,1.0,3.0,4.5,Affordable,Affordable Units,NaN,NaN
3,3705 10th Ave,NaN,C,5,"7,460",Apartments,Uptown San Diego,San Diego,0.22,2001,1.0,1.0,2.3,Affordable,Rent Subsidized,1.60,8.0
4,2104-2106 Abbott St,NaN,C,2,"1,944",Apartments,Ocean Beach,San Diego,0.11,1950,2.0,1.0,4.3,Market/Affordable,Affordable Units,NaN,NaN

In [5]:
# List of addresses with names
# addresses_with_names = [
#     {"name": "Atkinson Hall", "address": "3195 Voigt Dr, La Jolla, CA 92093"},
#     {"name": "Canyonview Aquatic Center", "address": "3302 Voigt Dr, San Diego, CA 92121"}
# ]

addresses_with_names = []

def fillAddressStruct(row):
    propName = row['Building Name']
    propAddress = row['Address']
    addresses_with_names.append({"name": propName, "address": propAddress})
    return None 

df.apply(fillAddressStruct, axis=1);

In [13]:
# Geocode each address above and save to CSV
idx = 1
# with open("geocoded_addresses.csv", mode='w', newline='') as 
with open("geocoded_costar_addresses.csv", mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow([0, 'Name', 'Address', 'Latitude', 'Longitude'])

    for item in addresses_with_names:
        name = item['name']
        address = item['address']
        address = address + ', San Diego'

        lat, lon = geocode_address(address)

        writer.writerow([idx, name, address, lat, lon])

        idx += 1

# print("Geocoded addresses saved to 'geocoded_addresses.csv'.")
print("Saved!")

Saved!

In [14]:
geocode_address("3534 5th Ave, San Diego")

(32.742218, -117.160729)